### ISSUE TITLE
implement getters to get ballot feed info from Ethereum and IPFS

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/contracts#48]
From IPFS:
- [x] title
- [ ] author name
- [x] date of creation

From Ethereum: 
- [x] number of `yes` votes on ballot (option1)
- [x] number of `no` votes on ballot (option2)

Contextual information that we need to retrieve based on the users' eth address: 
- [ ] number votes on ballot + selected option
- [ ] available delegated and not cast votes on ballots

**Comment by virgile-dev** [comment]
Ballot feed: 
<img width="285" alt="capture d ecran 2018-04-22 a 12 32 08" src="https://user-images.githubusercontent.com/11473995/39094058-2fc16824-462a-11e8-8f91-fbf1523289bb.png">

**Comment by marc-wagner** [comment]
"Contextual information that we need to retrieve based on the users' eth address" : info is not persisted in current datamodel in LiquidDemocracy.sol. 

votecount is not tallied from  individual votes, as in sovereign, but summed up at ballot level when vote is cast ( info on contributors is discarded) 

choice to 
1) extend datamodel or 
2) implement getter only partially

**Comment by aecc** [comment]
It's a better idea to extend the data model.
We need to persist such things as author name, date of creation, we can create different github issues for those if they don't exist yet. 
Also, there is a current restriction that will be kept like that for the moment, where a voter can give just a single vote. There us no ("voter", "ballot", "voted option") triplet stored yet, the data model needs to be modified to allow it.

**Comment by marc-wagner** [comment]
If someone has a datamodel of sovereign, it could be used for inspiration. T would also ease future integration.

**Comment by marc-wagner** [comment]
i extracted the datamodel from Sovereign as a starting point:
contracts (tally, votes cast on ballot, voters, ballots)
transactions ( delegation?)
users (votes cast, available...) 
we could use this as an interface to extend the contract data model?
[sovereign_datamodel.txt](https://github.com/DemocracyEarth/contracts/files/2006921/sovereign_datamodel.txt)

**Comment by marc-wagner** [comment]
what about this mapping:

Sovereign Collection | LiquidDemocracy struct
------------ | -------------
users | voter
contract | ballot
transaction | voteAllocation (new)

state of a ballot would be computed from individual voteAllocations.  so it would look something like this :

```json
{  
   "Sovereign::transactions":{  
      "mapping":"new, e.g. voteAllocation. a record of 1 vote being cast by sender to delegate or ballotOption",
      "input":{  
         "entityId":"sender ipfs hash"
      },
      "output":{  
         "entityId":"receiver ipfs hash"
      },
      "condition":{  
         "tags":[  

         ],
         "contract_id":"XSeehntRuosdtxZzq",
         "transferable":true,
         "portable":true
      }
   },
   "Sovereign::users":{  
      "mapping":"Contracts::Voter",
      "_id":"ipfs hash",
      "wallet":{  
         "balance":1131,
         "placed":0,
         "available":1131
      }
   },
   "Sovereign::contracts":{  
      "mapping":"Contracts::ballot",
      "_id":"XSeehntRuosdtxZzq",
      "title":"poll 1 . just yes / no answer",
      "tally":{  
         "choice":[  
            {  
               "ballot":"Yes"
            },
            {  
               "ballot":"No"
            }
         ]
      }
   }
}
```

i shrank the 'ballot' object to just a YES/NO label, but maybe someone can comment on whether the other attributes would be required?

```json
         "ballot":[  
            {  
               "executive":true,
               "mode":"AUTHORIZE",
               "_id":"1",
               "tick":true
            }
```
full analysis attached: 
[analysis_strip_sovereign_datamodel.txt](https://github.com/DemocracyEarth/contracts/files/2011033/analysis_strip_sovereign_datamodel.txt)
