### ISSUE TITLE
[Metamask] call contract revoke() vote function

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/contracts#55]
When user clicks on `revoke` button it should trigger a metamask transaction.

 - [ ] send json to IPFS to get hash
 - [x] implement API call with web3.js and construct transaction.

**Comment by virgile-dev** [comment]
Transaction status
<img width="885" alt="capture d ecran 2018-04-22 a 14 09 38" src="https://user-images.githubusercontent.com/11473995/39094855-d381e0f4-4636-11e8-85ec-3f19619115ff.png">

**Comment by aecc** [comment]
This should be working already. Closing...
